[global]
# Show debug information
developmentMode = false

# Configure data directory
dataDir = "data/"

[server]
# Server settings
port = 8501
baseUrlPath = ""
enableCORS = false
enableXsrfProtection = true

# File watcher settings
runOnSave = true
allowRunOnSave = true

# Upload settings
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Browser settings
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[theme]
# UI theme settings
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# Client settings
toolbarMode = "minimal"
showErrorDetails = true
caching = true

[runner]
# Runner settings
magicEnabled = true
installTracer = false
fixMatplotlib = true

# Fast reruns
fastReruns = true

# Post-script hook
postScriptGC = true

[logger]
# Logging settings
level = "info"
enableLogging = true
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s"

[deprecation]
# Deprecation warnings
showPyplotGlobalUse = false
showfileUploaderEncoding = false
# OpenAI API Configuration
[openai]
api_key = "your-openai-api-key-here"

# Google Sheets Configuration (Optional - for full functionality)
[google_sheets]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_KEY\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@your-project.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
spreadsheet_id = "your-spreadsheet-id"
